version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: true
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn
workflows:
  build:
    jobs:
      - build
