version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  pipeline:
    docker:
      - image: cimg/node:16.15.1
    working_directory: ~/recipes-web
    steps:
      - checkout
      - node/install-packages:
          check-cache: detect
          pkg-manager: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build modules
          command: |
            echo 'export CI=false' >> $BASH_ENV
            source $BASH_ENV
            yarn build

workflows:
  pipeline:
    jobs:
      - pipeline
